name = "stm32_gui"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
stm32_hal = "0.1.0-dev"
adl_middleware = "0.2.0"

#[configuration.values]
#cortex_m.core = "m4f"

[origin]
commit = "9fb1d7a89e611708fd1bdb1e06760c424bf6b9d6"
url = "git+https://github.com/GNAT-Academic-Program/stm32_gui.git"

